### PR TITLE
Inliner: Optional parameters for `load_data()`

### PR DESCRIPTION
**Pull request by thierrymoudiki**
Allow the use of optional parameters for  pandas`read_parquet` and `read_csv`

### CODE REVIEW

**Comment by Caceresenzo** [comment]
That actually a really cool idea!

Just to be sure, its for setting things like `engine=fastparquet` parameters right?

Also tell me when you think you finished your work, I will publish it in the next release as soon as you are done.

**Comment by Caceresenzo** [comment]
Also I know its not written anywhere but we are using [conventional commits](https://www.conventionalcommits.org/) here.

**Comment by thierrymoudiki** [comment]
> Just to be sure, its for setting things like `engine=fastparquet` parameters right?

Yes, exactly! 

I'll have a look at 'conventional commits'.

**Comment by thierrymoudiki** [comment]
I've just added the same `**kwargs` to `to_csv` and `to_parquet`. Maybe there are other places where this can be useful, but I haven't figured it out yet.

**Comment by Caceresenzo** [comment]
I dont think adding it to `utils.write` as useful as it is only used internally.

**Comment by thierrymoudiki** [comment]
> I dont think adding it to `utils.write` as useful as it is only used internally.

OK, should I delete it? Or you can alter the commit?

**Comment by Caceresenzo** [comment]
You can `git revert` it if you want.

Or I can do it if you want.
Just tell me when you think you finished your work, I will do the rest and prepare the release.

I also might move the `utils.read` changes directly into `Inliner.load_data`.

**Comment by thierrymoudiki** [comment]
No problem, you can do it please. That's all I needed (the `read_*`, for now).

**Pull request merged**
